// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-0whbPxe85BPfB6HlM0R0p-o6vAqnrE',
    appId: '1:1076135677437:web:546a307d36ac72756c9d94',
    messagingSenderId: '1076135677437',
    projectId: 'authtutorial-4f443',
    authDomain: 'authtutorial-4f443.firebaseapp.com',
    storageBucket: 'authtutorial-4f443.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFQp_kfh-JnngSf3KX84MwxMxZw_2J52E',
    appId: '1:1076135677437:android:7fdbfd4961d24b446c9d94',
    messagingSenderId: '1076135677437',
    projectId: 'authtutorial-4f443',
    storageBucket: 'authtutorial-4f443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpu1k_tJ_xGzsfC-xTB7bXDllp4D3BBHY',
    appId: '1:1076135677437:ios:cbe4380fa3933c006c9d94',
    messagingSenderId: '1076135677437',
    projectId: 'authtutorial-4f443',
    storageBucket: 'authtutorial-4f443.firebasestorage.app',
    iosBundleId: 'com.example.basicAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpu1k_tJ_xGzsfC-xTB7bXDllp4D3BBHY',
    appId: '1:1076135677437:ios:cbe4380fa3933c006c9d94',
    messagingSenderId: '1076135677437',
    projectId: 'authtutorial-4f443',
    storageBucket: 'authtutorial-4f443.firebasestorage.app',
    iosBundleId: 'com.example.basicAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn-0whbPxe85BPfB6HlM0R0p-o6vAqnrE',
    appId: '1:1076135677437:web:7a0e88273fc037566c9d94',
    messagingSenderId: '1076135677437',
    projectId: 'authtutorial-4f443',
    authDomain: 'authtutorial-4f443.firebaseapp.com',
    storageBucket: 'authtutorial-4f443.firebasestorage.app',
  );
}
